/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.UsuarioHibernateDao;
import entidades.Usuario;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;

/**
 *
 * @author dgsantos
 */
public class LoginUsuario extends javax.swing.JFrame implements KeyListener{

    /**
     * Creates new form LoginUsuario
     */
    public LoginUsuario() {
        initComponents();
        setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        txtDisplay = new javax.swing.JTextField();
        btn00 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn03 = new javax.swing.JButton();
        btn04 = new javax.swing.JButton();
        bnt05 = new javax.swing.JButton();
        btn06 = new javax.swing.JButton();
        btn07 = new javax.swing.JButton();
        btn08 = new javax.swing.JButton();
        btn09 = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnDel1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Login");

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        txtDisplay.setEditable(false);
        txtDisplay.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btn00.setBackground(new java.awt.Color(255, 255, 255));
        btn00.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn00.setText("0");
        btn00.setPreferredSize(new java.awt.Dimension(40, 40));
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });

        btn01.setBackground(new java.awt.Color(255, 255, 255));
        btn01.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn01.setText("1");
        btn01.setPreferredSize(new java.awt.Dimension(40, 40));
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });

        btn02.setBackground(new java.awt.Color(255, 255, 255));
        btn02.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn02.setText("2");
        btn02.setPreferredSize(new java.awt.Dimension(40, 40));
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });

        btn03.setBackground(new java.awt.Color(255, 255, 255));
        btn03.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn03.setText("3");
        btn03.setPreferredSize(new java.awt.Dimension(40, 40));
        btn03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn03ActionPerformed(evt);
            }
        });

        btn04.setBackground(new java.awt.Color(255, 255, 255));
        btn04.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn04.setText("4");
        btn04.setPreferredSize(new java.awt.Dimension(40, 40));
        btn04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn04ActionPerformed(evt);
            }
        });

        bnt05.setBackground(new java.awt.Color(255, 255, 255));
        bnt05.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bnt05.setText("5");
        bnt05.setPreferredSize(new java.awt.Dimension(40, 40));
        bnt05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt05ActionPerformed(evt);
            }
        });

        btn06.setBackground(new java.awt.Color(255, 255, 255));
        btn06.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn06.setText("6");
        btn06.setPreferredSize(new java.awt.Dimension(40, 40));
        btn06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn06ActionPerformed(evt);
            }
        });

        btn07.setBackground(new java.awt.Color(255, 255, 255));
        btn07.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn07.setText("7");
        btn07.setPreferredSize(new java.awt.Dimension(40, 40));
        btn07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn07ActionPerformed(evt);
            }
        });

        btn08.setBackground(new java.awt.Color(255, 255, 255));
        btn08.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn08.setText("8");
        btn08.setPreferredSize(new java.awt.Dimension(40, 40));
        btn08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn08ActionPerformed(evt);
            }
        });

        btn09.setBackground(new java.awt.Color(255, 255, 255));
        btn09.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn09.setText("9");
        btn09.setPreferredSize(new java.awt.Dimension(40, 40));
        btn09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn09ActionPerformed(evt);
            }
        });

        btnDel.setBackground(new java.awt.Color(153, 153, 255));
        btnDel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDel.setText("DEL");
        btnDel.setPreferredSize(new java.awt.Dimension(40, 40));
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnOk.setBackground(new java.awt.Color(204, 255, 204));
        btnOk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOk.setText("OK");
        btnOk.setPreferredSize(new java.awt.Dimension(40, 40));
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 102, 102));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.setPreferredSize(new java.awt.Dimension(40, 40));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnDel1.setBackground(new java.awt.Color(255, 204, 102));
        btnDel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDel1.setText("CLR");
        btnDel1.setPreferredSize(new java.awt.Dimension(40, 40));
        btnDel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(btn07, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn08, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn09, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(btn04, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bnt05, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn06, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn03, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtDisplay))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn07, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn08, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn09, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn04, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnt05, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn06, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn03, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(288, 372));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        login();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        imputNumero(1);// TODO add your handling code here:
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        imputNumero(2);
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn03ActionPerformed
imputNumero(3);        // TODO add your handling code here:
    }//GEN-LAST:event_btn03ActionPerformed

    private void btn04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn04ActionPerformed
imputNumero(4);        // TODO add your handling code here:
    }//GEN-LAST:event_btn04ActionPerformed

    private void bnt05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt05ActionPerformed
imputNumero(5);        // TODO add your handling code here:
    }//GEN-LAST:event_bnt05ActionPerformed

    private void btn06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn06ActionPerformed
imputNumero(6);        // TODO add your handling code here:
    }//GEN-LAST:event_btn06ActionPerformed

    private void btn07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn07ActionPerformed
imputNumero(7);        // TODO add your handling code here:
    }//GEN-LAST:event_btn07ActionPerformed

    private void btn08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn08ActionPerformed
   imputNumero(8);
    }//GEN-LAST:event_btn08ActionPerformed

    private void btn09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn09ActionPerformed
imputNumero(9);        // TODO add your handling code here:
    }//GEN-LAST:event_btn09ActionPerformed

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
imputNumero(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btn00ActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
deleteNumero();
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnDel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDel1ActionPerformed
limparDisplay();
    }//GEN-LAST:event_btnDel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUsuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt05;
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn03;
    private javax.swing.JButton btn04;
    private javax.swing.JButton btn06;
    private javax.swing.JButton btn07;
    private javax.swing.JButton btn08;
    private javax.swing.JButton btn09;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDel1;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnOk;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables

    private void setup(){
        
        
        pnlPrincipal.addKeyListener(this);
        bnt05.addKeyListener(this);
    btn00.addKeyListener(this);
    btn01.addKeyListener(this);
    btn02.addKeyListener(this);
    btn03.addKeyListener(this);
    btn04.addKeyListener(this);
    btn06.addKeyListener(this);
   btn07.addKeyListener(this);
    btn08.addKeyListener(this);
    btn09.addKeyListener(this);
    btnDel.addKeyListener(this);
    btnDel1.addKeyListener(this);
   btnExit.addKeyListener(this);
    btnOk.addKeyListener(this);    
    txtDisplay.addKeyListener(this);
          
        
    }
    
    
    public void imputNumero(int botao){
        
        
        String texto = txtDisplay.getText();
        texto = texto+botao;
        txtDisplay.setText(texto);
        
        
        
        
    }
    
    
    
    private void login() {
       
        
        
        String matricula = txtDisplay.getText();
        
        Usuario usuario = new Usuario();
        usuario.setMatricula(matricula);
        Usuario efetuarLogin = new UsuarioHibernateDao().efetuarLogin(usuario);
        
        
        if(efetuarLogin!=null){
            new LoginUsuarioConfirmaView(efetuarLogin).setVisible(true);
            limparDisplay();
            
        }else{
            JOptionPane.showMessageDialog(null, "Usuário não existe");
            limparDisplay();
        }
        
    }

    private void deleteNumero() {
       
        String txt = txtDisplay.getText();
        
        if(txt.length()>0){
            txt = txt.substring(0,txt.length()-1);
        }
        
        
        txtDisplay.setText(txt);
        
    }

    private void limparDisplay() {
        txtDisplay.setText("");
    }

    @Override
    public void keyTyped(KeyEvent e) {
       
    }

    @Override
    public void keyPressed(KeyEvent e) {
              if(e.getKeyCode()==KeyEvent.VK_0 || e.getKeyCode()==KeyEvent.VK_NUMPAD0){
            imputNumero(0);
        } else if(e.getKeyCode()==KeyEvent.VK_1 || e.getKeyCode()==KeyEvent.VK_NUMPAD1){
            imputNumero(1);
        }
        else if(e.getKeyCode()==KeyEvent.VK_2 || e.getKeyCode()==KeyEvent.VK_NUMPAD2){
            imputNumero(2);
        }
        else if(e.getKeyCode()==KeyEvent.VK_3 || e.getKeyCode()==KeyEvent.VK_NUMPAD3){
            imputNumero(3);
        }
        else if(e.getKeyCode()==KeyEvent.VK_4 || e.getKeyCode()==KeyEvent.VK_NUMPAD4){
            imputNumero(4);
        }
        else if(e.getKeyCode()==KeyEvent.VK_5 || e.getKeyCode()==KeyEvent.VK_NUMPAD5){
            imputNumero(5);
        }
        else if(e.getKeyCode()==KeyEvent.VK_6 || e.getKeyCode()==KeyEvent.VK_NUMPAD6){
            imputNumero(6);
        }
        else if(e.getKeyCode()==KeyEvent.VK_7 || e.getKeyCode()==KeyEvent.VK_NUMPAD7){
            imputNumero(7);
        }
        else if(e.getKeyCode()==KeyEvent.VK_8 || e.getKeyCode()==KeyEvent.VK_NUMPAD8){
            imputNumero(8);
        }
        else if(e.getKeyCode()==KeyEvent.VK_9 || e.getKeyCode()==KeyEvent.VK_NUMPAD9){
            imputNumero(9);
        }else if(e.getKeyCode()== KeyEvent.VK_ENTER){
            login();
        }else if(e.getKeyCode()==KeyEvent.VK_DELETE){
            deleteNumero();
        }
              else if(e.getKeyCode()==KeyEvent.VK_ESCAPE){
            limparDisplay();
        }
              
              
        
        
        
        
    }

    @Override
    public void keyReleased(KeyEvent e) {
      
    }
}
