//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Scheduler.java
//  @ Date : 20/5/2013
//  @ Author : 
//
//



package entities;

import java.util.ArrayList;


public class Scheduler {
	public ArrayList<Equipamento> listaRecursos;
	public void schedule(Object Usuario) {
	
	}
}
